# Generated by Django 3.0.3 on 2020-07-05 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BankDetails',
            fields=[
                ('bank_id', models.AutoField(primary_key=True, serialize=False)),
                ('bank_name', models.CharField(blank=True, max_length=49, null=True)),
                ('bank_ifsc', models.CharField(blank=True, max_length=11, null=True)),
                ('bank_branch', models.CharField(blank=True, max_length=74, null=True)),
                ('bank_address', models.CharField(blank=True, max_length=195, null=True)),
                ('bank_city', models.CharField(blank=True, max_length=50, null=True)),
                ('bank_district', models.CharField(blank=True, max_length=50, null=True)),
                ('bank_state', models.CharField(blank=True, max_length=26, null=True)),
            ],
        ),
    ]
